services:
  catalogue:
    build: ./catalogue
    image: raviteja471/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  mongodb:
    build: ./Mongodb
    image: raviteja471/mongodb:1.0.0
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: true