services:
  catalogue:
    build: ./catalogue
    image: raviteja471/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: raviteja471/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    build: ./cart
    image: raviteja471/cart:1.0.0
    container_name: cart
    depends_on:
      - redis
      - catalogue

  frontend:
    build: ./frontend
    image: raviteja471/frontend:1.0.0
    container_name: frontend
    depends_on:
      - catalogue
      - cart
      - user
  mongodb:
    build: ./Mongodb
    image: raviteja471/mongodb:1.0.0
    container_name: mongodb
  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: true